######################################################################
# Automatically generated by qmake (3.0) Mon Jun 22 21:34:16 2015
######################################################################

TEMPLATE = app
TARGET = Qt
INCLUDEPATH += .

QT += serialport widgets

# Input
HEADERS += Arduino.h Interface.h Fader.h
SOURCES += Arduino.cc Interface.cc Fader.cc main.cc
